CREATE TABLE APIUsers(
    ID INT NOT NULL AUTO_INCREMENT,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    Name VARCHAR(48),
    SecretKey VARCHAR(36),
    APIAuthorization VARCHAR(36),
    EncryptionKey VARCHAR(24),
    IsEnabled BIT DEFAULT 1,
    CONSTRAINT PK_API_User_ID PRIMARY KEY (ID)
);

CREATE TABLE EndPoints(
    ID INT NOT NULL AUTO_INCREMENT,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    EndPointURL VARCHAR(256),
    IsEnabled BIT DEFAULT 1,
    CONSTRAINT PK_End_Point_ID PRIMARY KEY (ID)
);

INSERT INTO EndPoints(EndPointURL) VALUES ('/api/v1');

CREATE TABLE RequestLogs(
    ID INT NOT NULL AUTO_INCREMENT,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    IPv4 VARCHAR(15),
    APIUserID INT NOT NULL,
    EndPointID INT NOT NULL,
    Method VARCHAR(6),
    Data VARCHAR(5000),
    CONSTRAINT FK_Request_Log_API_User FOREIGN KEY (APIUserID)
    REFERENCES APIUsers(ID),
    CONSTRAINT FK_Request_Log_End_Point FOREIGN KEY (EndPointID)
    REFERENCES EndPoints(ID),
    CONSTRAINT PK_Request_Log_ID PRIMARY KEY (ID)
);

